### PR TITLE
👷‍♂️ Add __init__.py to unittests

### PR DESCRIPTION
**Pull request by schachmett**
Make unittests a real python package so imports are handled correctly (especially by VS code's test explorer).

See also https://stackoverflow.com/a/48804718

### CODE REVIEW

**Comment by hf-kklein** [comment]
works on pycharm ✅ besides that I don't care :)

Anyways it will be helpful to also add the file to our https://github.com/Hochfrequenz/python_template_repository
because all new repos derived from the template will ship without the `__init__.py` as of now

**Review by hf-kklein — APPROVED** [review]
maybe you can add a comment to the __init__.py file

```python
# this file is necessary for the VS Code Python Test Explorer
# For more details see...
```

**Comment by schachmett** [comment]
How about the comment that I added now? Considering that only this addition allows running `$ pytest unittests` (which vscode does) on the module in the first place, it seems like a more general issue. 
[This](https://docs.pytest.org/en/6.2.x/usage.html) explains the reasoning behind using __init__.py in pytest and even goes into specific detail for tox projects. It seems that we are safe anyway because our source is inside the non-package `src` folder.

**Comment by hf-kklein** [comment]
Thanks for the comment in the `__init__.py` file! I'm pretty sure it won't hurt, hence my approval!
Pytest says
> This layout [with a separate src directory for the package itself] prevents a lot of common pitfalls and has many benefits

**Comment by hf-kklein** [comment]
sorry, ich habe gerade den dependabot gemerged 🙈

**Review by HF-FSteinkamp — APPROVED** [review]

**Pull request merged**
